" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/dotfiles/vimrc/plugins/plugins.vim
source ~/dotfiles/vimrc/plugins/configs.vim
source ~/dotfiles/vimrc/settings/basic.vim
source ~/dotfiles/vimrc/settings/style.vim
source ~/dotfiles/vimrc/mappings/mappings.vim
"source ~/.vim_runtime/vimrcs/basic.vim
"source ~/.vim_runtime/vimrcs/filetypes.vim
"source ~/.vim_runtime/vimrcs/plugins_config.vim
"source ~/.vim_runtime/vimrcs/extended.vim
try
  "source ~/.vim_runtime/my_configs.vim
catch
endtry
